### ISSUE TITLE
[BUG] kipartman crashes if PCBNEW (kicad library) is notaccessible

### ISSUE THREAD

**Issue by auphofBSF** [turdusmerula/kipartman#12]
see: a simple fix, I will raise it as a Pull Request for Master
[IMP] Error Handler if running without Kicad pcbnew  https://github.com/turdusmerula/kipartman/commit/eb3b0cfe344885d7c6c7d6aba571e8a2a4b9e716

**Comment by auphofBSF** [comment]
I see I can't just create a Pull request for this commit, I will have to create a separate branch. I suggest we leave it till branch Issue#8-FIXTEST is validated

**Comment by turdusmerula** [comment]
This is a first step, next will be to add an item in the configuration window to allow non system path for kicad.
Maybe we should turn this bug to a feature?

**Comment by auphofBSF** [comment]
Agreed, 
However the non system path will possibly have issues on MSW, I really struggled to find a way to run use PCBnew from another instance of Python. from what I remember it was failing on some dll's. 
maybe we have to integrate parts of PCBnew into kipartman. 
For now if we merge this and then create a [FEATURE] I can try and look further into the issues on implementation on MSW.

**Comment by auphofBSF** [comment]
This can be closed as is now merged. 

@turdusmerula will you raise a [FEATURE] around enhanced configuration window, what else are your thoughts to go in there

**Comment by turdusmerula** [comment]
Opened feature #17 as a reminder

2017-11-27 20:12 GMT+01:00 Anthony Uphof <notifications@github.com>:
