### ISSUE TITLE
[BUG] Kipartman cannot start if Internet Connection down

### ISSUE THREAD

**Issue by auphofBSF** [turdusmerula/kipartman#21]
Kipartman fails around checking for currencies if internet connection is down
Look at handling , Startup, Octopart and SnapEDA queries in event of internet connection unavailable

**Comment by turdusmerula** [comment]
More generally there is no kind of check whether there is a valid
connection to kipartbase or any other website, it should be improved.
For now every call to rest api of any kind is made synchronously, that
means if a link is really slow or goes timeout then kipartman turns to very
bad user experience. I have in my plans to enable asynchronous
interruptible calls to improve this too.

2017-12-23 9:05 GMT+01:00 Anthony Uphof <notifications@github.com>:
