### ISSUE TITLE
[FEATURE] Enable adding parameter columns in part view 

### ISSUE THREAD

**Issue by turdusmerula** [turdusmerula/kipartman#5]

**Comment by turdusmerula** [comment]
See pull request #10

**Comment by auphofBSF** [comment]
In trying out this feature I had a few issues, I believe these are fixed and ok for inclusion in master. I will issue a pull request. on branch:
Issue#5-FEATURE,-bugs-and-regression-fixes

**Comment by turdusmerula** [comment]
Regression merged, I close the issue.
